<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
		<PackageReference Include="Z.Blazor.Diagrams" Version="3.0.2" />
		<PackageReference Include="Blazor.ContextMenu" Version="2.0.0" />
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <_ContentIncludedByDefault Remove="Pages\Action\Create.razor" />
	  <_ContentIncludedByDefault Remove="Pages\Action\Delete.razor" />
	  <_ContentIncludedByDefault Remove="Pages\Action\Index.razor" />
	</ItemGroup>

</Project>
